// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	health "github.com/tokyolab/dogx/apps/system/api/internal/handler/health"
	"github.com/tokyolab/dogx/apps/system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Liveness probe
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				// Readiness probe
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
	)
}
