// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	auth "github.com/tokyolab/dogx/apps/system/api/internal/handler/auth"
	health "github.com/tokyolab/dogx/apps/system/api/internal/handler/health"
	"github.com/tokyolab/dogx/apps/system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Sign in with username and password
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// Rotate the refresh token and issue new credentials
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth},
			[]rest.Route{
				{
					// Revoke the current session
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					// Revoke all sessions of the current user
					Method:  http.MethodPost,
					Path:    "/auth/logout-all",
					Handler: auth.LogoutAllHandler(serverCtx),
				},
				{
					// Return the current signed-in user
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: auth.CurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Liveness probe
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				// Readiness probe
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
	)
}
