// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	api "github.com/tokyolab/dogx/apps/system/api/internal/handler/api"
	auth "github.com/tokyolab/dogx/apps/system/api/internal/handler/auth"
	health "github.com/tokyolab/dogx/apps/system/api/internal/handler/health"
	role "github.com/tokyolab/dogx/apps/system/api/internal/handler/role"
	"github.com/tokyolab/dogx/apps/system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Authorization},
			[]rest.Route{
				{
					// List API authorization resources
					Method:  http.MethodPost,
					Path:    "/api/list",
					Handler: api.ListAPIsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Sign in with username and password
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// Rotate the refresh token and issue new credentials
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth},
			[]rest.Route{
				{
					// Change the current user password and revoke all sessions
					Method:  http.MethodPost,
					Path:    "/auth/change-password",
					Handler: auth.ChangePasswordHandler(serverCtx),
				},
				{
					// Revoke the current session
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					// Revoke all sessions of the current user
					Method:  http.MethodPost,
					Path:    "/auth/logout-all",
					Handler: auth.LogoutAllHandler(serverCtx),
				},
				{
					// Return the current signed-in user
					Method:  http.MethodPost,
					Path:    "/auth/me",
					Handler: auth.CurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Liveness probe
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				// Readiness probe
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Authorization},
			[]rest.Route{
				{
					// Get API authorizations assigned to a role
					Method:  http.MethodPost,
					Path:    "/role/api/get",
					Handler: role.GetRoleAPIsHandler(serverCtx),
				},
				{
					// Replace the complete API authorization set for a role
					Method:  http.MethodPost,
					Path:    "/role/api/update",
					Handler: role.UpdateRoleAPIsHandler(serverCtx),
				},
				{
					// Get a role
					Method:  http.MethodPost,
					Path:    "/role/get",
					Handler: role.GetRoleHandler(serverCtx),
				},
				{
					// List roles
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: role.ListRolesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
