syntax = "proto3";

package system;

option go_package = "./system";

message ReadyRequest {}

message ReadyResponse {
  string status = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
  string ip_address = 3;
  string user_agent = 4;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
  int64 expires_in = 3;
}

message RefreshCredentialsRequest {
  string refresh_token = 1;
}

message EmptyResponse {}

message CurrentUserRequest {
  int64 user_id = 1;
}

message CurrentUserResponse {
  int64 id = 1;
  string username = 2;
  string nickname = 3;
}

message RevokeSessionRequest {
  int64 user_id = 1;
  string session_id = 2;
}

message RevokeUserSessionsRequest {
  int64 user_id = 1;
}

message ChangePasswordRequest {
  int64 user_id = 1;
  string current_password = 2;
  string new_password = 3;
}

service System {
  rpc CheckReady(ReadyRequest) returns (ReadyResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc RefreshCredentials(RefreshCredentialsRequest) returns (LoginResponse);
  rpc GetCurrentUser(CurrentUserRequest) returns (CurrentUserResponse);
  rpc RevokeSession(RevokeSessionRequest) returns (EmptyResponse);
  rpc RevokeUserSessions(RevokeUserSessionsRequest) returns (EmptyResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (EmptyResponse);
}
