-- +goose Up
CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(32),
    status SMALLINT NOT NULL DEFAULT 1,
    last_login_at TIMESTAMPTZ,
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_sys_user_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE sys_user IS '系统用户表';
COMMENT ON COLUMN sys_user.id IS '用户主键';
COMMENT ON COLUMN sys_user.username IS '登录账号';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.nickname IS '用户昵称';
COMMENT ON COLUMN sys_user.email IS '电子邮箱';
COMMENT ON COLUMN sys_user.phone IS '手机号码';
COMMENT ON COLUMN sys_user.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.remark IS '备注';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user.deleted_at IS '软删除时间，NULL表示未删除';

CREATE UNIQUE INDEX uk_sys_user_username_active
    ON sys_user (LOWER(username))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_sys_user_email_active
    ON sys_user (LOWER(email))
    WHERE email IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX uk_sys_user_phone_active
    ON sys_user (phone)
    WHERE phone IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX idx_sys_user_deleted_at ON sys_user (deleted_at);

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    sort INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_sys_role_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE sys_role IS '系统角色表';
COMMENT ON COLUMN sys_role.id IS '角色主键';
COMMENT ON COLUMN sys_role.code IS '角色编码';
COMMENT ON COLUMN sys_role.name IS '角色名称';
COMMENT ON COLUMN sys_role.description IS '角色描述';
COMMENT ON COLUMN sys_role.sort IS '显示顺序，数值越小越靠前';
COMMENT ON COLUMN sys_role.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';
COMMENT ON COLUMN sys_role.deleted_at IS '软删除时间，NULL表示未删除';

CREATE UNIQUE INDEX uk_sys_role_code_active
    ON sys_role (LOWER(code))
    WHERE deleted_at IS NULL;

CREATE INDEX idx_sys_role_deleted_at ON sys_role (deleted_at);

CREATE TABLE sys_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    menu_type SMALLINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    route_name VARCHAR(128) NOT NULL DEFAULT '',
    path VARCHAR(255) NOT NULL DEFAULT '',
    component VARCHAR(255) NOT NULL DEFAULT '',
    permission VARCHAR(128) NOT NULL DEFAULT '',
    icon VARCHAR(128) NOT NULL DEFAULT '',
    sort INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    status SMALLINT NOT NULL DEFAULT 1,
    keep_alive BOOLEAN NOT NULL DEFAULT FALSE,
    external BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_sys_menu_type CHECK (menu_type IN (1, 2, 3)),
    CONSTRAINT ck_sys_menu_status CHECK (status IN (0, 1)),
    CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id)
        REFERENCES sys_menu (id) ON DELETE RESTRICT
);

COMMENT ON TABLE sys_menu IS '系统菜单与权限标识表';
COMMENT ON COLUMN sys_menu.id IS '菜单主键';
COMMENT ON COLUMN sys_menu.parent_id IS '父菜单主键，NULL表示根节点';
COMMENT ON COLUMN sys_menu.menu_type IS '菜单类型：1目录，2页面，3按钮';
COMMENT ON COLUMN sys_menu.name IS '菜单名称';
COMMENT ON COLUMN sys_menu.route_name IS '前端路由名称';
COMMENT ON COLUMN sys_menu.path IS '前端路由路径';
COMMENT ON COLUMN sys_menu.component IS '前端组件路径';
COMMENT ON COLUMN sys_menu.permission IS '前端权限标识';
COMMENT ON COLUMN sys_menu.icon IS '菜单图标';
COMMENT ON COLUMN sys_menu.sort IS '显示顺序，数值越小越靠前';
COMMENT ON COLUMN sys_menu.visible IS '是否在菜单中显示：false隐藏，true显示';
COMMENT ON COLUMN sys_menu.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_menu.keep_alive IS '是否缓存页面：false否，true是';
COMMENT ON COLUMN sys_menu.external IS '是否为外链：false否，true是';
COMMENT ON COLUMN sys_menu.remark IS '备注';
COMMENT ON COLUMN sys_menu.created_at IS '创建时间';
COMMENT ON COLUMN sys_menu.updated_at IS '更新时间';
COMMENT ON COLUMN sys_menu.deleted_at IS '软删除时间，NULL表示未删除';

CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_sys_menu_deleted_at ON sys_menu (deleted_at);
CREATE INDEX idx_sys_menu_permission ON sys_menu (permission)
    WHERE permission <> '' AND deleted_at IS NULL;

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id)
        REFERENCES sys_role (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_user_role IS '用户角色关联表';
COMMENT ON COLUMN sys_user_role.user_id IS '用户主键';
COMMENT ON COLUMN sys_user_role.role_id IS '角色主键';
COMMENT ON COLUMN sys_user_role.created_at IS '关联创建时间';

CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);

CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, menu_id),
    CONSTRAINT fk_sys_role_menu_role FOREIGN KEY (role_id)
        REFERENCES sys_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_menu_menu FOREIGN KEY (menu_id)
        REFERENCES sys_menu (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_role_menu IS '角色菜单关联表';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色主键';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单主键';
COMMENT ON COLUMN sys_role_menu.created_at IS '关联创建时间';

CREATE INDEX idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);

-- +goose Down
DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_user;
