-- +goose Up
CREATE TABLE sys_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(128) NOT NULL,
    sort INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_sys_department_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_sys_department_sort CHECK (sort >= 0),
    CONSTRAINT ck_sys_department_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE sys_department IS '系统部门表';
COMMENT ON COLUMN sys_department.id IS '部门主键';
COMMENT ON COLUMN sys_department.parent_id IS '父部门主键，NULL表示根部门';
COMMENT ON COLUMN sys_department.name IS '部门名称';
COMMENT ON COLUMN sys_department.sort IS '显示顺序，数值越小越靠前';
COMMENT ON COLUMN sys_department.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_department.remark IS '备注';
COMMENT ON COLUMN sys_department.created_at IS '创建时间';
COMMENT ON COLUMN sys_department.updated_at IS '更新时间';
COMMENT ON COLUMN sys_department.deleted_at IS '软删除时间，NULL表示未删除';

CREATE UNIQUE INDEX uk_sys_department_parent_name_active
    ON sys_department (COALESCE(parent_id, 0), LOWER(name))
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sys_department_parent_sort
    ON sys_department (parent_id, sort, id)
    WHERE deleted_at IS NULL;

ALTER TABLE sys_user ADD COLUMN department_id BIGINT;
COMMENT ON COLUMN sys_user.department_id IS '主部门主键，NULL表示历史账号尚未分配部门';
CREATE INDEX idx_sys_user_department_id ON sys_user (department_id) WHERE deleted_at IS NULL;

INSERT INTO sys_department (name, sort, status, remark)
VALUES ('默认部门', 0, 1, '系统初始化默认部门');

UPDATE sys_user
SET department_id = (SELECT id FROM sys_department WHERE name = '默认部门' ORDER BY id DESC LIMIT 1)
WHERE department_id IS NULL;

INSERT INTO sys_api (service_name, api_group, name, path, method, is_required, status, remark)
VALUES
 ('system-api', '部门管理', '查询部门列表', '/department/list', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '部门管理', '查询部门详情', '/department/get', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '部门管理', '新增部门', '/department/create', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '部门管理', '修改部门', '/department/update', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '部门管理', '修改部门状态', '/department/status/update', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '部门管理', '删除部门', '/department/delete', 'POST', FALSE, 1, '系统内置部门管理接口'),
 ('system-api', '用户管理', '查询用户部门选项', '/user/department/options', 'POST', FALSE, 1, '用户部门选择与筛选');

-- If the original system directory was deleted, keep the new page reachable
-- as a root page instead of silently omitting its menu entry.
INSERT INTO sys_menu (app_code, parent_id, menu_type, name, route_name, path, component, icon, sort)
VALUES ('admin_web', (SELECT id FROM sys_menu WHERE app_code = 'admin_web' AND route_name = 'SystemManagement' AND deleted_at IS NULL),
        2, '部门管理', 'DepartmentManagement', '/system/department', 'system/department/index', 'lucide:network', 40);

-- +goose Down
-- +goose StatementBegin
DO $$
DECLARE
    department_menu_id BIGINT;
BEGIN
    SELECT id INTO department_menu_id FROM sys_menu
    WHERE app_code = 'admin_web' AND route_name = 'DepartmentManagement' AND path = '/system/department' AND deleted_at IS NULL;
    IF EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = department_menu_id) THEN
        RAISE EXCEPTION 'cannot roll back department menu while other menus reference it';
    END IF;
    DELETE FROM sys_role_menu WHERE menu_id = department_menu_id;
    DELETE FROM sys_menu WHERE id = department_menu_id;
END;
$$;
-- +goose StatementEnd
DELETE FROM casbin_rule WHERE ptype = 'p' AND v2 = 'POST' AND v1 IN (
 '/department/list', '/department/get', '/department/create', '/department/update',
 '/department/status/update', '/department/delete', '/user/department/options'
);
DELETE FROM sys_api WHERE method = 'POST' AND path IN (
 '/department/list', '/department/get', '/department/create', '/department/update',
 '/department/status/update', '/department/delete', '/user/department/options'
);
DROP INDEX IF EXISTS idx_sys_user_department_id;
ALTER TABLE sys_user DROP COLUMN IF EXISTS department_id;
DROP INDEX IF EXISTS idx_sys_department_parent_sort;
DROP INDEX IF EXISTS uk_sys_department_parent_name_active;
DROP TABLE IF EXISTS sys_department;
