-- +goose Up
CREATE TABLE sys_dictionary (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(128) NOT NULL CHECK (BTRIM(name) <> ''),
 code VARCHAR(64) NOT NULL CHECK (code ~ '^[a-z][a-z0-9_-]{0,63}$'),
 remark VARCHAR(500) NOT NULL DEFAULT '',
 status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0,1)),
 is_public BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_sys_dictionary_code_active ON sys_dictionary(code) WHERE deleted_at IS NULL;

CREATE TABLE sys_dictionary_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dictionary_id BIGINT NOT NULL,
 label VARCHAR(128) NOT NULL CHECK (BTRIM(label) <> ''),
 value VARCHAR(128) NOT NULL CHECK (BTRIM(value) <> ''),
 sort INTEGER NOT NULL DEFAULT 0 CHECK (sort >= 0),
 remark VARCHAR(500) NOT NULL DEFAULT '',
 status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0,1)),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uk_sys_dictionary_item_value_active ON sys_dictionary_item(dictionary_id,value) WHERE deleted_at IS NULL;
CREATE INDEX idx_sys_dictionary_item_sort ON sys_dictionary_item(dictionary_id,sort,id) WHERE deleted_at IS NULL;

COMMENT ON TABLE sys_dictionary IS '系统字典，动态业务选项，不代替程序枚举';
COMMENT ON TABLE sys_dictionary_item IS '系统字典项，业务保存稳定的字符串值';
COMMENT ON COLUMN sys_dictionary.id IS '主键';
COMMENT ON COLUMN sys_dictionary.name IS '字典名称';
COMMENT ON COLUMN sys_dictionary.code IS '稳定字典编码，创建后不可修改';
COMMENT ON COLUMN sys_dictionary.remark IS '备注';
COMMENT ON COLUMN sys_dictionary.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_dictionary.is_public IS '允许匿名读取，默认不公开';
COMMENT ON COLUMN sys_dictionary.created_at IS '创建时间';
COMMENT ON COLUMN sys_dictionary.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dictionary.deleted_at IS '软删除时间';
COMMENT ON COLUMN sys_dictionary_item.id IS '主键';
COMMENT ON COLUMN sys_dictionary_item.dictionary_id IS '所属字典主键';
COMMENT ON COLUMN sys_dictionary_item.label IS '显示标签';
COMMENT ON COLUMN sys_dictionary_item.value IS '稳定字典值，创建后不可修改';
COMMENT ON COLUMN sys_dictionary_item.sort IS '排序，小值优先';
COMMENT ON COLUMN sys_dictionary_item.remark IS '备注';
COMMENT ON COLUMN sys_dictionary_item.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_dictionary_item.created_at IS '创建时间';
COMMENT ON COLUMN sys_dictionary_item.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dictionary_item.deleted_at IS '软删除时间';

INSERT INTO sys_api (service_name, api_group, name, path, method, is_required, status, remark) VALUES
('system-api','字典管理','查询字典列表','/dictionary/list','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','查询字典详情','/dictionary/get','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','新增字典','/dictionary/create','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','修改字典','/dictionary/update','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','修改字典状态','/dictionary/status/update','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','删除字典','/dictionary/delete','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','查询字典项列表','/dictionary/item/list','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','查询字典项详情','/dictionary/item/get','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','新增字典项','/dictionary/item/create','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','修改字典项','/dictionary/item/update','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','修改字典项状态','/dictionary/item/status/update','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','删除字典项','/dictionary/item/delete','POST',FALSE,1,'系统内置字典管理接口'),
('system-api','字典管理','刷新字典缓存','/dictionary/cache/clear','POST',FALSE,1,'系统内置字典管理接口');
INSERT INTO sys_menu (app_code,parent_id,menu_type,name,route_name,path,component,icon,sort)
VALUES ('admin_web',(SELECT id FROM sys_menu WHERE app_code='admin_web' AND route_name='SystemManagement' AND deleted_at IS NULL),
2,'字典管理','DictionaryManagement','/system/dictionary','system/dictionary/index','lucide:book-open',50);

-- +goose Down
-- +goose StatementBegin
DO $$
DECLARE dictionary_menu_id BIGINT;
BEGIN
 SELECT id INTO dictionary_menu_id FROM sys_menu WHERE app_code='admin_web' AND route_name='DictionaryManagement' AND path='/system/dictionary' AND deleted_at IS NULL;
 IF EXISTS (SELECT 1 FROM sys_menu WHERE parent_id=dictionary_menu_id) THEN
  RAISE EXCEPTION 'cannot roll back dictionary menu while child menus exist';
 END IF;
 DELETE FROM sys_role_menu WHERE menu_id=dictionary_menu_id;
 DELETE FROM sys_menu WHERE id=dictionary_menu_id;
END;
$$;
-- +goose StatementEnd
DELETE FROM casbin_rule WHERE ptype='p' AND v2='POST' AND v1 IN ('/dictionary/list','/dictionary/get','/dictionary/create','/dictionary/update','/dictionary/status/update','/dictionary/delete','/dictionary/item/list','/dictionary/item/get','/dictionary/item/create','/dictionary/item/update','/dictionary/item/status/update','/dictionary/item/delete','/dictionary/cache/clear');
DELETE FROM sys_api WHERE method='POST' AND path IN ('/dictionary/list','/dictionary/get','/dictionary/create','/dictionary/update','/dictionary/status/update','/dictionary/delete','/dictionary/item/list','/dictionary/item/get','/dictionary/item/create','/dictionary/item/update','/dictionary/item/status/update','/dictionary/item/delete','/dictionary/cache/clear');
DROP TABLE sys_dictionary_item;
DROP TABLE sys_dictionary;
