-- +goose Up
ALTER TABLE sys_menu
    ADD COLUMN app_code VARCHAR(64) NOT NULL DEFAULT 'admin_web';

COMMENT ON COLUMN sys_menu.app_code IS '前端应用编码，例如admin_web或admin_mobile';

ALTER TABLE sys_menu
    DROP CONSTRAINT ck_sys_menu_type,
    DROP CONSTRAINT fk_sys_menu_parent;

ALTER TABLE sys_menu
    ADD CONSTRAINT ck_sys_menu_app_code_not_blank CHECK (BTRIM(app_code) <> ''),
    ADD CONSTRAINT ck_sys_menu_type CHECK (menu_type IN (1, 2, 3)),
    ADD CONSTRAINT ck_sys_menu_element_permission CHECK (
        (menu_type = 3 AND BTRIM(permission) <> '') OR
        (menu_type IN (1, 2) AND permission = '')
    ),
    ADD CONSTRAINT ck_sys_menu_element_route CHECK (
        menu_type <> 3 OR (route_name = '' AND path = '' AND component = '')
    ),
    ADD CONSTRAINT uk_sys_menu_id_app_code UNIQUE (id, app_code),
    ADD CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id, app_code)
        REFERENCES sys_menu (id, app_code) ON DELETE RESTRICT;

COMMENT ON TABLE sys_menu IS '系统多应用目录、页面与页面元素表';
COMMENT ON COLUMN sys_menu.menu_type IS '菜单类型：1目录，2页面，3页面元素';
COMMENT ON COLUMN sys_menu.permission IS '前端页面元素权限标识';

CREATE UNIQUE INDEX uk_sys_menu_app_route_name_active
    ON sys_menu (app_code, LOWER(route_name))
    WHERE route_name <> '' AND deleted_at IS NULL;

CREATE UNIQUE INDEX uk_sys_menu_app_path_active
    ON sys_menu (app_code, path)
    WHERE path <> '' AND deleted_at IS NULL;

CREATE INDEX idx_sys_menu_app_parent_sort
    ON sys_menu (app_code, parent_id, sort)
    WHERE deleted_at IS NULL;

CREATE TABLE sys_api (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(64) NOT NULL,
    api_group VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    path VARCHAR(100) NOT NULL,
    method VARCHAR(16) NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    status SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_sys_api_method_upper CHECK (BTRIM(method) <> '' AND method = UPPER(method)),
    CONSTRAINT ck_sys_api_path CHECK (path LIKE '/%'),
    CONSTRAINT ck_sys_api_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE sys_api IS '系统接口授权资源目录表';
COMMENT ON COLUMN sys_api.id IS '接口资源主键';
COMMENT ON COLUMN sys_api.service_name IS '所属API服务名称';
COMMENT ON COLUMN sys_api.api_group IS '授权界面中的业务分组';
COMMENT ON COLUMN sys_api.name IS '接口显示名称';
COMMENT ON COLUMN sys_api.path IS '不含查询参数的HTTP路径';
COMMENT ON COLUMN sys_api.method IS '大写HTTP方法';
COMMENT ON COLUMN sys_api.is_required IS '是否为所有普通角色必需接口';
COMMENT ON COLUMN sys_api.status IS '状态：0停用，1启用';
COMMENT ON COLUMN sys_api.remark IS '备注';
COMMENT ON COLUMN sys_api.created_at IS '创建时间';
COMMENT ON COLUMN sys_api.updated_at IS '更新时间';
COMMENT ON COLUMN sys_api.deleted_at IS '软删除时间，NULL表示未删除';

CREATE UNIQUE INDEX uk_sys_api_method_path_active
    ON sys_api (method, path)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_sys_api_service_group
    ON sys_api (service_name, api_group, id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_sys_api_deleted_at ON sys_api (deleted_at);

CREATE TABLE casbin_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype VARCHAR(100) NOT NULL DEFAULT '',
    v0 VARCHAR(100) NOT NULL DEFAULT '',
    v1 VARCHAR(100) NOT NULL DEFAULT '',
    v2 VARCHAR(100) NOT NULL DEFAULT '',
    v3 VARCHAR(100) NOT NULL DEFAULT '',
    v4 VARCHAR(100) NOT NULL DEFAULT '',
    v5 VARCHAR(100) NOT NULL DEFAULT ''
);

COMMENT ON TABLE casbin_rule IS 'Casbin官方GORM Adapter策略持久化表';
COMMENT ON COLUMN casbin_rule.id IS '策略主键';
COMMENT ON COLUMN casbin_rule.ptype IS '策略类型，例如p或g';
COMMENT ON COLUMN casbin_rule.v0 IS 'Casbin策略字段v0';
COMMENT ON COLUMN casbin_rule.v1 IS 'Casbin策略字段v1';
COMMENT ON COLUMN casbin_rule.v2 IS 'Casbin策略字段v2';
COMMENT ON COLUMN casbin_rule.v3 IS 'Casbin策略字段v3';
COMMENT ON COLUMN casbin_rule.v4 IS 'Casbin策略字段v4';
COMMENT ON COLUMN casbin_rule.v5 IS 'Casbin策略字段v5';

CREATE UNIQUE INDEX idx_casbin_rule
    ON casbin_rule (ptype, v0, v1, v2, v3, v4, v5);

CREATE INDEX idx_casbin_rule_ptype_v0 ON casbin_rule (ptype, v0);

-- +goose Down
DROP TABLE IF EXISTS casbin_rule;
DROP TABLE IF EXISTS sys_api;

DROP INDEX IF EXISTS idx_sys_menu_app_parent_sort;
DROP INDEX IF EXISTS uk_sys_menu_app_path_active;
DROP INDEX IF EXISTS uk_sys_menu_app_route_name_active;

ALTER TABLE sys_menu
    DROP CONSTRAINT fk_sys_menu_parent,
    DROP CONSTRAINT uk_sys_menu_id_app_code,
    DROP CONSTRAINT ck_sys_menu_element_route,
    DROP CONSTRAINT ck_sys_menu_element_permission,
    DROP CONSTRAINT ck_sys_menu_type;

ALTER TABLE sys_menu
    ADD CONSTRAINT ck_sys_menu_type CHECK (menu_type IN (1, 2, 3));

ALTER TABLE sys_menu
    DROP COLUMN app_code,
    ADD CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id)
        REFERENCES sys_menu (id) ON DELETE RESTRICT;

COMMENT ON TABLE sys_menu IS '系统菜单与权限标识表';
COMMENT ON COLUMN sys_menu.menu_type IS '菜单类型：1目录，2页面，3按钮';
COMMENT ON COLUMN sys_menu.permission IS '前端权限标识';
