-- +goose Up
CREATE TABLE sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(64) NOT NULL,
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(64) NOT NULL DEFAULT '',
    ip_address VARCHAR(45) NOT NULL DEFAULT '',
    user_agent VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_login_log_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE SET NULL
);

COMMENT ON TABLE sys_login_log IS '用户登录审计日志表';
COMMENT ON COLUMN sys_login_log.id IS '登录日志主键';
COMMENT ON COLUMN sys_login_log.user_id IS '用户主键，未知账号或用户删除后为NULL';
COMMENT ON COLUMN sys_login_log.username IS '登录时提交的账号快照';
COMMENT ON COLUMN sys_login_log.success IS '是否登录成功：false失败，true成功';
COMMENT ON COLUMN sys_login_log.failure_reason IS '失败原因标识，成功时为空字符串';
COMMENT ON COLUMN sys_login_log.ip_address IS '客户端IP地址';
COMMENT ON COLUMN sys_login_log.user_agent IS '客户端User-Agent';
COMMENT ON COLUMN sys_login_log.created_at IS '登录发生时间';

CREATE INDEX idx_sys_login_log_user_created_at
    ON sys_login_log (user_id, created_at DESC);

CREATE INDEX idx_sys_login_log_created_at
    ON sys_login_log (created_at DESC);

CREATE INDEX idx_sys_login_log_username_created_at
    ON sys_login_log (LOWER(username), created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS sys_login_log;
