// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package systemclient

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/types/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	APIInfo                   = system.APIInfo
	ChangePasswordRequest     = system.ChangePasswordRequest
	CreateRoleRequest         = system.CreateRoleRequest
	CreateRoleResponse        = system.CreateRoleResponse
	CurrentUserRequest        = system.CurrentUserRequest
	CurrentUserResponse       = system.CurrentUserResponse
	DeleteRoleRequest         = system.DeleteRoleRequest
	EmptyResponse             = system.EmptyResponse
	GetRoleAPIsRequest        = system.GetRoleAPIsRequest
	GetRoleAPIsResponse       = system.GetRoleAPIsResponse
	GetRoleRequest            = system.GetRoleRequest
	GetRoleResponse           = system.GetRoleResponse
	ListAPIsRequest           = system.ListAPIsRequest
	ListAPIsResponse          = system.ListAPIsResponse
	ListRolesRequest          = system.ListRolesRequest
	ListRolesResponse         = system.ListRolesResponse
	LoginRequest              = system.LoginRequest
	LoginResponse             = system.LoginResponse
	ReadyRequest              = system.ReadyRequest
	ReadyResponse             = system.ReadyResponse
	RefreshCredentialsRequest = system.RefreshCredentialsRequest
	ReplaceRoleAPIsRequest    = system.ReplaceRoleAPIsRequest
	RevokeSessionRequest      = system.RevokeSessionRequest
	RevokeUserSessionsRequest = system.RevokeUserSessionsRequest
	RoleInfo                  = system.RoleInfo
	UpdateRoleRequest         = system.UpdateRoleRequest
	UpdateRoleStatusRequest   = system.UpdateRoleStatusRequest

	System interface {
		CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error)
		RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
		ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
		GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateRoleStatus(ctx context.Context, in *UpdateRoleStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ListAPIs(ctx context.Context, in *ListAPIsRequest, opts ...grpc.CallOption) (*ListAPIsResponse, error)
		GetRoleAPIs(ctx context.Context, in *GetRoleAPIsRequest, opts ...grpc.CallOption) (*GetRoleAPIsResponse, error)
		ReplaceRoleAPIs(ctx context.Context, in *ReplaceRoleAPIsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CheckReady(ctx, in, opts...)
}

func (m *defaultSystem) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultSystem) RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RefreshCredentials(ctx, in, opts...)
}

func (m *defaultSystem) GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}

func (m *defaultSystem) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeSession(ctx, in, opts...)
}

func (m *defaultSystem) RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeUserSessions(ctx, in, opts...)
}

func (m *defaultSystem) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultSystem) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultSystem) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

func (m *defaultSystem) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultSystem) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultSystem) UpdateRoleStatus(ctx context.Context, in *UpdateRoleStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateRoleStatus(ctx, in, opts...)
}

func (m *defaultSystem) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultSystem) ListAPIs(ctx context.Context, in *ListAPIsRequest, opts ...grpc.CallOption) (*ListAPIsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListAPIs(ctx, in, opts...)
}

func (m *defaultSystem) GetRoleAPIs(ctx context.Context, in *GetRoleAPIsRequest, opts ...grpc.CallOption) (*GetRoleAPIsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetRoleAPIs(ctx, in, opts...)
}

func (m *defaultSystem) ReplaceRoleAPIs(ctx context.Context, in *ReplaceRoleAPIsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ReplaceRoleAPIs(ctx, in, opts...)
}
