// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package systemclient

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/types/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	APIInfo                       = system.APIInfo
	ChangePasswordRequest         = system.ChangePasswordRequest
	CreateDepartmentRequest       = system.CreateDepartmentRequest
	CreateDepartmentResponse      = system.CreateDepartmentResponse
	CreateMenuRequest             = system.CreateMenuRequest
	CreateMenuResponse            = system.CreateMenuResponse
	CreateRoleRequest             = system.CreateRoleRequest
	CreateRoleResponse            = system.CreateRoleResponse
	CreateUserRequest             = system.CreateUserRequest
	CreateUserResponse            = system.CreateUserResponse
	CurrentUserRequest            = system.CurrentUserRequest
	CurrentUserResponse           = system.CurrentUserResponse
	DeleteDepartmentRequest       = system.DeleteDepartmentRequest
	DeleteMenuRequest             = system.DeleteMenuRequest
	DeleteRoleRequest             = system.DeleteRoleRequest
	DeleteUserRequest             = system.DeleteUserRequest
	DepartmentInfo                = system.DepartmentInfo
	EmptyResponse                 = system.EmptyResponse
	GetDepartmentRequest          = system.GetDepartmentRequest
	GetDepartmentResponse         = system.GetDepartmentResponse
	GetMenuRequest                = system.GetMenuRequest
	GetMenuResponse               = system.GetMenuResponse
	GetRoleAPIsRequest            = system.GetRoleAPIsRequest
	GetRoleAPIsResponse           = system.GetRoleAPIsResponse
	GetRoleMenusRequest           = system.GetRoleMenusRequest
	GetRoleMenusResponse          = system.GetRoleMenusResponse
	GetRoleRequest                = system.GetRoleRequest
	GetRoleResponse               = system.GetRoleResponse
	GetUserRequest                = system.GetUserRequest
	GetUserResponse               = system.GetUserResponse
	ListAPIsRequest               = system.ListAPIsRequest
	ListAPIsResponse              = system.ListAPIsResponse
	ListDepartmentsRequest        = system.ListDepartmentsRequest
	ListDepartmentsResponse       = system.ListDepartmentsResponse
	ListMenusRequest              = system.ListMenusRequest
	ListMenusResponse             = system.ListMenusResponse
	ListNavigationMenusRequest    = system.ListNavigationMenusRequest
	ListNavigationMenusResponse   = system.ListNavigationMenusResponse
	ListRolesRequest              = system.ListRolesRequest
	ListRolesResponse             = system.ListRolesResponse
	ListUserRoleOptionsResponse   = system.ListUserRoleOptionsResponse
	ListUsersRequest              = system.ListUsersRequest
	ListUsersResponse             = system.ListUsersResponse
	LoginRequest                  = system.LoginRequest
	LoginResponse                 = system.LoginResponse
	MenuFields                    = system.MenuFields
	MenuInfo                      = system.MenuInfo
	NavigationMenu                = system.NavigationMenu
	ProfileResponse               = system.ProfileResponse
	ReadyRequest                  = system.ReadyRequest
	ReadyResponse                 = system.ReadyResponse
	RefreshCredentialsRequest     = system.RefreshCredentialsRequest
	ReplaceRoleAPIsRequest        = system.ReplaceRoleAPIsRequest
	ReplaceRoleMenusRequest       = system.ReplaceRoleMenusRequest
	ReplaceUserRolesRequest       = system.ReplaceUserRolesRequest
	ResetUserPasswordRequest      = system.ResetUserPasswordRequest
	RevokeSessionRequest          = system.RevokeSessionRequest
	RevokeUserSessionsRequest     = system.RevokeUserSessionsRequest
	RoleInfo                      = system.RoleInfo
	UpdateDepartmentRequest       = system.UpdateDepartmentRequest
	UpdateDepartmentStatusRequest = system.UpdateDepartmentStatusRequest
	UpdateMenuRequest             = system.UpdateMenuRequest
	UpdateMenuStatusRequest       = system.UpdateMenuStatusRequest
	UpdateProfileRequest          = system.UpdateProfileRequest
	UpdateRoleRequest             = system.UpdateRoleRequest
	UpdateRoleStatusRequest       = system.UpdateRoleStatusRequest
	UpdateUserRequest             = system.UpdateUserRequest
	UpdateUserStatusRequest       = system.UpdateUserStatusRequest
	UserInfo                      = system.UserInfo
	UserRoleInfo                  = system.UserRoleInfo

	System interface {
		GetProfile(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		GetRoleMenus(ctx context.Context, in *GetRoleMenusRequest, opts ...grpc.CallOption) (*GetRoleMenusResponse, error)
		ReplaceRoleMenus(ctx context.Context, in *ReplaceRoleMenusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ListNavigationMenus(ctx context.Context, in *ListNavigationMenusRequest, opts ...grpc.CallOption) (*ListNavigationMenusResponse, error)
		ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error)
		GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error)
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateMenuStatus(ctx context.Context, in *UpdateMenuStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error)
		RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
		ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
		GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateRoleStatus(ctx context.Context, in *UpdateRoleStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ListAPIs(ctx context.Context, in *ListAPIsRequest, opts ...grpc.CallOption) (*ListAPIsResponse, error)
		GetRoleAPIs(ctx context.Context, in *GetRoleAPIsRequest, opts ...grpc.CallOption) (*GetRoleAPIsResponse, error)
		ReplaceRoleAPIs(ctx context.Context, in *ReplaceRoleAPIsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ReplaceUserRoles(ctx context.Context, in *ReplaceUserRolesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ListUserRoleOptions(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListUserRoleOptionsResponse, error)
		ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error)
		GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error)
		CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error)
		UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateDepartmentStatus(ctx context.Context, in *UpdateDepartmentStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) GetProfile(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultSystem) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultSystem) GetRoleMenus(ctx context.Context, in *GetRoleMenusRequest, opts ...grpc.CallOption) (*GetRoleMenusResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetRoleMenus(ctx, in, opts...)
}

func (m *defaultSystem) ReplaceRoleMenus(ctx context.Context, in *ReplaceRoleMenusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ReplaceRoleMenus(ctx, in, opts...)
}

func (m *defaultSystem) ListNavigationMenus(ctx context.Context, in *ListNavigationMenusRequest, opts ...grpc.CallOption) (*ListNavigationMenusResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListNavigationMenus(ctx, in, opts...)
}

func (m *defaultSystem) ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListMenus(ctx, in, opts...)
}

func (m *defaultSystem) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}

func (m *defaultSystem) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultSystem) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultSystem) UpdateMenuStatus(ctx context.Context, in *UpdateMenuStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateMenuStatus(ctx, in, opts...)
}

func (m *defaultSystem) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultSystem) CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CheckReady(ctx, in, opts...)
}

func (m *defaultSystem) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultSystem) RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RefreshCredentials(ctx, in, opts...)
}

func (m *defaultSystem) GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}

func (m *defaultSystem) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeSession(ctx, in, opts...)
}

func (m *defaultSystem) RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeUserSessions(ctx, in, opts...)
}

func (m *defaultSystem) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultSystem) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultSystem) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

func (m *defaultSystem) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultSystem) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultSystem) UpdateRoleStatus(ctx context.Context, in *UpdateRoleStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateRoleStatus(ctx, in, opts...)
}

func (m *defaultSystem) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultSystem) ListAPIs(ctx context.Context, in *ListAPIsRequest, opts ...grpc.CallOption) (*ListAPIsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListAPIs(ctx, in, opts...)
}

func (m *defaultSystem) GetRoleAPIs(ctx context.Context, in *GetRoleAPIsRequest, opts ...grpc.CallOption) (*GetRoleAPIsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetRoleAPIs(ctx, in, opts...)
}

func (m *defaultSystem) ReplaceRoleAPIs(ctx context.Context, in *ReplaceRoleAPIsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ReplaceRoleAPIs(ctx, in, opts...)
}

func (m *defaultSystem) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultSystem) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultSystem) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultSystem) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultSystem) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

func (m *defaultSystem) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultSystem) ReplaceUserRoles(ctx context.Context, in *ReplaceUserRolesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ReplaceUserRoles(ctx, in, opts...)
}

func (m *defaultSystem) ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ResetUserPassword(ctx, in, opts...)
}

func (m *defaultSystem) ListUserRoleOptions(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListUserRoleOptionsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListUserRoleOptions(ctx, in, opts...)
}

func (m *defaultSystem) ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ListDepartments(ctx, in, opts...)
}

func (m *defaultSystem) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetDepartment(ctx, in, opts...)
}

func (m *defaultSystem) CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CreateDepartment(ctx, in, opts...)
}

func (m *defaultSystem) UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateDepartment(ctx, in, opts...)
}

func (m *defaultSystem) UpdateDepartmentStatus(ctx context.Context, in *UpdateDepartmentStatusRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.UpdateDepartmentStatus(ctx, in, opts...)
}

func (m *defaultSystem) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.DeleteDepartment(ctx, in, opts...)
}
