// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package systemclient

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/types/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePasswordRequest     = system.ChangePasswordRequest
	CurrentUserRequest        = system.CurrentUserRequest
	CurrentUserResponse       = system.CurrentUserResponse
	EmptyResponse             = system.EmptyResponse
	LoginRequest              = system.LoginRequest
	LoginResponse             = system.LoginResponse
	ReadyRequest              = system.ReadyRequest
	ReadyResponse             = system.ReadyResponse
	RefreshCredentialsRequest = system.RefreshCredentialsRequest
	RevokeSessionRequest      = system.RevokeSessionRequest
	RevokeUserSessionsRequest = system.RevokeUserSessionsRequest

	System interface {
		CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error)
		RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) CheckReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.CheckReady(ctx, in, opts...)
}

func (m *defaultSystem) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultSystem) RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RefreshCredentials(ctx, in, opts...)
}

func (m *defaultSystem) GetCurrentUser(ctx context.Context, in *CurrentUserRequest, opts ...grpc.CallOption) (*CurrentUserResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}

func (m *defaultSystem) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeSession(ctx, in, opts...)
}

func (m *defaultSystem) RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.RevokeUserSessions(ctx, in, opts...)
}

func (m *defaultSystem) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}
