// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package server

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/internal/logic"
	"github.com/tokyolab/dogx/apps/system/rpc/internal/svc"
	"github.com/tokyolab/dogx/apps/system/rpc/types/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) CheckReady(ctx context.Context, in *system.ReadyRequest) (*system.ReadyResponse, error) {
	l := logic.NewCheckReadyLogic(ctx, s.svcCtx)
	return l.CheckReady(in)
}

func (s *SystemServer) Login(ctx context.Context, in *system.LoginRequest) (*system.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *SystemServer) RefreshCredentials(ctx context.Context, in *system.RefreshCredentialsRequest) (*system.LoginResponse, error) {
	l := logic.NewRefreshCredentialsLogic(ctx, s.svcCtx)
	return l.RefreshCredentials(in)
}

func (s *SystemServer) GetCurrentUser(ctx context.Context, in *system.CurrentUserRequest) (*system.CurrentUserResponse, error) {
	l := logic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}

func (s *SystemServer) RevokeSession(ctx context.Context, in *system.RevokeSessionRequest) (*system.EmptyResponse, error) {
	l := logic.NewRevokeSessionLogic(ctx, s.svcCtx)
	return l.RevokeSession(in)
}

func (s *SystemServer) RevokeUserSessions(ctx context.Context, in *system.RevokeUserSessionsRequest) (*system.EmptyResponse, error) {
	l := logic.NewRevokeUserSessionsLogic(ctx, s.svcCtx)
	return l.RevokeUserSessions(in)
}

func (s *SystemServer) ChangePassword(ctx context.Context, in *system.ChangePasswordRequest) (*system.EmptyResponse, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *SystemServer) CreateRole(ctx context.Context, in *system.CreateRoleRequest) (*system.CreateRoleResponse, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *SystemServer) ListRoles(ctx context.Context, in *system.ListRolesRequest) (*system.ListRolesResponse, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *SystemServer) GetRole(ctx context.Context, in *system.GetRoleRequest) (*system.GetRoleResponse, error) {
	l := logic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

func (s *SystemServer) UpdateRole(ctx context.Context, in *system.UpdateRoleRequest) (*system.EmptyResponse, error) {
	l := logic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *SystemServer) UpdateRoleStatus(ctx context.Context, in *system.UpdateRoleStatusRequest) (*system.EmptyResponse, error) {
	l := logic.NewUpdateRoleStatusLogic(ctx, s.svcCtx)
	return l.UpdateRoleStatus(in)
}

func (s *SystemServer) DeleteRole(ctx context.Context, in *system.DeleteRoleRequest) (*system.EmptyResponse, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *SystemServer) ListAPIs(ctx context.Context, in *system.ListAPIsRequest) (*system.ListAPIsResponse, error) {
	l := logic.NewListAPIsLogic(ctx, s.svcCtx)
	return l.ListAPIs(in)
}

func (s *SystemServer) GetRoleAPIs(ctx context.Context, in *system.GetRoleAPIsRequest) (*system.GetRoleAPIsResponse, error) {
	l := logic.NewGetRoleAPIsLogic(ctx, s.svcCtx)
	return l.GetRoleAPIs(in)
}

func (s *SystemServer) ReplaceRoleAPIs(ctx context.Context, in *system.ReplaceRoleAPIsRequest) (*system.EmptyResponse, error) {
	l := logic.NewReplaceRoleAPIsLogic(ctx, s.svcCtx)
	return l.ReplaceRoleAPIs(in)
}

func (s *SystemServer) ListUsers(ctx context.Context, in *system.ListUsersRequest) (*system.ListUsersResponse, error) {
	l := logic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *SystemServer) GetUser(ctx context.Context, in *system.GetUserRequest) (*system.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *SystemServer) CreateUser(ctx context.Context, in *system.CreateUserRequest) (*system.CreateUserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *SystemServer) UpdateUser(ctx context.Context, in *system.UpdateUserRequest) (*system.EmptyResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *SystemServer) UpdateUserStatus(ctx context.Context, in *system.UpdateUserStatusRequest) (*system.EmptyResponse, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

func (s *SystemServer) DeleteUser(ctx context.Context, in *system.DeleteUserRequest) (*system.EmptyResponse, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *SystemServer) ReplaceUserRoles(ctx context.Context, in *system.ReplaceUserRolesRequest) (*system.EmptyResponse, error) {
	l := logic.NewReplaceUserRolesLogic(ctx, s.svcCtx)
	return l.ReplaceUserRoles(in)
}

func (s *SystemServer) ResetUserPassword(ctx context.Context, in *system.ResetUserPasswordRequest) (*system.EmptyResponse, error) {
	l := logic.NewResetUserPasswordLogic(ctx, s.svcCtx)
	return l.ResetUserPassword(in)
}

func (s *SystemServer) ListUserRoleOptions(ctx context.Context, in *system.ListRolesRequest) (*system.ListUserRoleOptionsResponse, error) {
	l := logic.NewListUserRoleOptionsLogic(ctx, s.svcCtx)
	return l.ListUserRoleOptions(in)
}
