// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package server

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/internal/logic"
	"github.com/tokyolab/dogx/apps/system/rpc/internal/svc"
	"github.com/tokyolab/dogx/apps/system/rpc/types/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) CheckReady(ctx context.Context, in *system.ReadyRequest) (*system.ReadyResponse, error) {
	l := logic.NewCheckReadyLogic(ctx, s.svcCtx)
	return l.CheckReady(in)
}

func (s *SystemServer) Login(ctx context.Context, in *system.LoginRequest) (*system.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *SystemServer) RefreshCredentials(ctx context.Context, in *system.RefreshCredentialsRequest) (*system.LoginResponse, error) {
	l := logic.NewRefreshCredentialsLogic(ctx, s.svcCtx)
	return l.RefreshCredentials(in)
}

func (s *SystemServer) GetCurrentUser(ctx context.Context, in *system.CurrentUserRequest) (*system.CurrentUserResponse, error) {
	l := logic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}

func (s *SystemServer) RevokeSession(ctx context.Context, in *system.RevokeSessionRequest) (*system.EmptyResponse, error) {
	l := logic.NewRevokeSessionLogic(ctx, s.svcCtx)
	return l.RevokeSession(in)
}

func (s *SystemServer) RevokeUserSessions(ctx context.Context, in *system.RevokeUserSessionsRequest) (*system.EmptyResponse, error) {
	l := logic.NewRevokeUserSessionsLogic(ctx, s.svcCtx)
	return l.RevokeUserSessions(in)
}

func (s *SystemServer) ChangePassword(ctx context.Context, in *system.ChangePasswordRequest) (*system.EmptyResponse, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *SystemServer) ListRoles(ctx context.Context, in *system.ListRolesRequest) (*system.ListRolesResponse, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *SystemServer) GetRole(ctx context.Context, in *system.GetRoleRequest) (*system.GetRoleResponse, error) {
	l := logic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

func (s *SystemServer) ListAPIs(ctx context.Context, in *system.ListAPIsRequest) (*system.ListAPIsResponse, error) {
	l := logic.NewListAPIsLogic(ctx, s.svcCtx)
	return l.ListAPIs(in)
}

func (s *SystemServer) GetRoleAPIs(ctx context.Context, in *system.GetRoleAPIsRequest) (*system.GetRoleAPIsResponse, error) {
	l := logic.NewGetRoleAPIsLogic(ctx, s.svcCtx)
	return l.GetRoleAPIs(in)
}

func (s *SystemServer) ReplaceRoleAPIs(ctx context.Context, in *system.ReplaceRoleAPIsRequest) (*system.EmptyResponse, error) {
	l := logic.NewReplaceRoleAPIsLogic(ctx, s.svcCtx)
	return l.ReplaceRoleAPIs(in)
}
