// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: system.proto

package server

import (
	"context"

	"github.com/tokyolab/dogx/apps/system/rpc/internal/logic"
	"github.com/tokyolab/dogx/apps/system/rpc/internal/svc"
	"github.com/tokyolab/dogx/apps/system/rpc/types/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) CheckReady(ctx context.Context, in *system.ReadyRequest) (*system.ReadyResponse, error) {
	l := logic.NewCheckReadyLogic(ctx, s.svcCtx)
	return l.CheckReady(in)
}
