// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type APIItem struct {
	Id          int64  `json:"id"`
	ServiceName string `json:"serviceName"`
	Group       string `json:"group"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	IsRequired  bool   `json:"isRequired"`
	Status      int64  `json:"status"`
	Remark      string `json:"remark"`
}

type APIListReq struct {
	Keyword     string `json:"keyword,optional" validate:"max=128"`
	ServiceName string `json:"serviceName,optional" validate:"max=64"`
	Group       string `json:"group,optional" validate:"max=64"`
}

type APIListResp struct {
	Items []APIItem `json:"items"`
}

type ChangePasswordReq struct {
	CurrentPassword string `json:"currentPassword" validate:"required,max=128"`
	NewPassword     string `json:"newPassword" validate:"required,min=12,max=128"`
}

type CreateRoleReq struct {
	Code        string `json:"code" validate:"required,max=64"`
	Name        string `json:"name" validate:"required,max=64"`
	Description string `json:"description,optional" validate:"max=500"`
	Sort        int64  `json:"sort" validate:"gte=0,lte=2147483647"`
	Status      int64  `json:"status" validate:"oneof=0 1"`
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type CurrentUserResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}

type EmptyResp struct {
}

type GetRoleAPIsReq struct {
	RoleId int64 `json:"roleId" validate:"gt=0"`
}

type GetRoleAPIsResp struct {
	ApiIds []int64 `json:"apiIds"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type IDReq struct {
	Id int64 `json:"id" validate:"gt=0"`
}

type IDsReq struct {
	Ids []int64 `json:"ids" validate:"min=1,dive,gt=0"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required,max=64"`
	Password string `json:"password" validate:"required,max=128"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type PageMeta struct {
	Total int64 `json:"total"`
}

type PageReq struct {
	Page     int64 `json:"page" validate:"gte=1"`
	PageSize int64 `json:"pageSize" validate:"gte=1,lte=200"`
}

type ReadyResp struct {
	Status string `json:"status"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken" validate:"required,max=256"`
}

type RoleItem struct {
	Id          int64  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Sort        int64  `json:"sort"`
	Status      int64  `json:"status"`
	IsSystem    bool   `json:"isSystem"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type RoleListReq struct {
	Page     int64  `json:"page" validate:"gte=1"`
	PageSize int64  `json:"pageSize" validate:"gte=1,lte=200"`
	Keyword  string `json:"keyword,optional" validate:"max=128"`
}

type RoleListResp struct {
	Items []RoleItem `json:"items"`
	Total int64      `json:"total"`
}

type UpdateRoleAPIsReq struct {
	RoleId int64   `json:"roleId" validate:"gt=0"`
	ApiIds []int64 `json:"apiIds" validate:"dive,gt=0"`
}

type UpdateRoleReq struct {
	Id          int64  `json:"id" validate:"gt=0"`
	Code        string `json:"code" validate:"required,max=64"`
	Name        string `json:"name" validate:"required,max=64"`
	Description string `json:"description,optional" validate:"max=500"`
	Sort        int64  `json:"sort" validate:"gte=0,lte=2147483647"`
}

type UpdateRoleStatusReq struct {
	Id     int64 `json:"id" validate:"gt=0"`
	Status int64 `json:"status" validate:"oneof=0 1"`
}
