// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type ReadyResp struct {
	Status string `json:"status"`
}
