// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type APIItem struct {
	Id          int64  `json:"id"`
	ServiceName string `json:"serviceName"`
	Group       string `json:"group"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	IsRequired  bool   `json:"isRequired"`
	Status      int64  `json:"status"`
	Remark      string `json:"remark"`
}

type APIListReq struct {
	Keyword     string `json:"keyword,optional"`
	ServiceName string `json:"serviceName,optional"`
	Group       string `json:"group,optional"`
}

type APIListResp struct {
	Items []APIItem `json:"items"`
}

type ChangePasswordReq struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateRoleReq struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Sort        int64  `json:"sort"`
	Status      int64  `json:"status"`
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type CurrentUserResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}

type EmptyResp struct {
}

type GetRoleAPIsReq struct {
	RoleId int64 `json:"roleId"`
}

type GetRoleAPIsResp struct {
	ApiIds []int64 `json:"apiIds"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type IDReq struct {
	Id int64 `json:"id"`
}

type IDsReq struct {
	Ids []int64 `json:"ids"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type PageMeta struct {
	Total int64 `json:"total"`
}

type PageReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ReadyResp struct {
	Status string `json:"status"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RoleItem struct {
	Id          int64  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Sort        int64  `json:"sort"`
	Status      int64  `json:"status"`
	IsSystem    bool   `json:"isSystem"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type RoleListReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Keyword  string `json:"keyword,optional"`
}

type RoleListResp struct {
	Items []RoleItem `json:"items"`
	Total int64      `json:"total"`
}

type UpdateRoleAPIsReq struct {
	RoleId int64   `json:"roleId"`
	ApiIds []int64 `json:"apiIds"`
}

type UpdateRoleReq struct {
	Id          int64  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Sort        int64  `json:"sort"`
}

type UpdateRoleStatusReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}
